language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
services:
  rabbitmq
  
cache:
  directories:
    - $HOME/.m2
sudo: false
install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -B install
script: ./travis_script.sh

