language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: ./gradlew assemble
script: ./gradlew build
